import type { LinuxQuestion } from "./linux-questions";

export const NMAP_QUESTIONS: LinuxQuestion[] = [
  // ─── Introduction to Nmap (1-10) ───
  { id: 1, prompt: "What does Nmap stand for?", options: ["Network Monitor and Probe", "Network Mapper", "Node Management and Port", "Network Management Application Protocol"], correctAnswer: "Network Mapper", explanation: "Nmap stands for Network Mapper. It was created by Gordon Lyon (Fyodor) in 1997 and is the most widely used open-source network scanner.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 2, prompt: "Which scan type does Nmap use by default when run as root?", options: ["TCP Connect (-sT)", "SYN scan (-sS)", "UDP scan (-sU)", "ACK scan (-sA)"], correctAnswer: "SYN scan (-sS)", explanation: "When run with root/administrator privileges, Nmap defaults to SYN scan (-sS), also called a half-open or stealth scan.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 3, prompt: "Why do many Nmap scan types require root/administrator privileges?", options: ["Nmap is a root-only application", "They craft raw IP packets at the network level", "They require access to the password database", "They need to modify routing tables"], correctAnswer: "They craft raw IP packets at the network level", explanation: "Scan types like -sS need to craft and send raw IP packets, which requires direct access to the network interface, only possible with root/admin privileges.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 4, prompt: "What flag enables the aggressive scan that combines OS detection, version detection, scripts, and traceroute?", options: ["-sV", "-O", "-A", "-T4"], correctAnswer: "-A", explanation: "-A enables aggressive mode which includes: -O (OS detection), -sV (version detection), -sC (default scripts), and --traceroute.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 5, prompt: "Which scan type works without root privileges?", options: ["SYN scan (-sS)", "TCP Connect scan (-sT)", "UDP scan (-sU)", "ACK scan (-sA)"], correctAnswer: "TCP Connect scan (-sT)", explanation: "TCP Connect scan (-sT) uses the OS's connect() syscall, which doesn't require raw packet access. It's the fallback when root is unavailable.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 6, prompt: "What command shows the installed Nmap version?", options: ["nmap -version", "nmap --version", "nmap -V", "nmap version"], correctAnswer: "nmap --version", explanation: "nmap --version displays the installed version and compile-time options.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 7, prompt: "What is the Nmap Scripting Engine (NSE) written in?", options: ["Python", "Perl", "Lua", "Ruby"], correctAnswer: "Lua", explanation: "NSE scripts are written in Lua, a lightweight scripting language. NSE allows extending Nmap with custom functionality.", topicSlug: "nmap-introduction", difficulty: "medium" },
  { id: 8, prompt: "How many of the most common ports does Nmap scan by default?", options: ["100", "500", "1000", "65535"], correctAnswer: "1000", explanation: "By default Nmap scans the top 1000 most common ports ranked by frequency of use in the nmap-services database.", topicSlug: "nmap-introduction", difficulty: "easy" },
  { id: 9, prompt: "What is the legal risk of scanning networks without permission?", options: ["None if the scan is passive", "Potential violation of the Computer Fraud and Abuse Act and similar laws", "Only a risk if you exploit a vulnerability", "No risk as long as you don't save the results"], correctAnswer: "Potential violation of the Computer Fraud and Abuse Act and similar laws", explanation: "Unauthorized port scanning is illegal in most jurisdictions. Always obtain written authorization before scanning any network.", topicSlug: "nmap-introduction", difficulty: "medium" },
  { id: 10, prompt: "Which verbosity flag shows results as they come in rather than waiting for the full scan?", options: ["-d", "-v", "--stats", "--live"], correctAnswer: "-v", explanation: "-v (or -vv for more) enables verbose mode, showing discovered open ports and other findings in real-time during the scan.", topicSlug: "nmap-introduction", difficulty: "easy" },

  // ─── Target Specification (11-20) ───
  { id: 11, prompt: "What CIDR notation scans all 256 hosts in the 192.168.1.x range?", options: ["192.168.1.0/16", "192.168.1.0/24", "192.168.1.0/32", "192.168.1.0/8"], correctAnswer: "192.168.1.0/24", explanation: "A /24 prefix covers the last octet (0-255), giving 256 IP addresses in the 192.168.1.0 network.", topicSlug: "target-specification", difficulty: "easy" },
  { id: 12, prompt: "What flag reads scan targets from a text file?", options: ["-iL", "-iF", "--targets", "--file"], correctAnswer: "-iL", explanation: "-iL (input list) reads hostnames, IP addresses, or CIDR notation from a text file, one per line.", topicSlug: "target-specification", difficulty: "easy" },
  { id: 13, prompt: "How do you exclude 192.168.1.1 when scanning the entire /24?", options: ["nmap 192.168.1.0/24 -skip 192.168.1.1", "nmap 192.168.1.0/24 --exclude 192.168.1.1", "nmap 192.168.1.0/24 -x 192.168.1.1", "nmap 192.168.1.2-254"], correctAnswer: "nmap 192.168.1.0/24 --exclude 192.168.1.1", explanation: "--exclude followed by IP addresses or ranges removes those hosts from the scan. Essential for protecting critical infrastructure.", topicSlug: "target-specification", difficulty: "easy" },
  { id: 14, prompt: "What does -n do in Nmap?", options: ["Use NULL scan instead of SYN", "Disable DNS reverse resolution", "Never send ICMP probes", "Enable no-port mode"], correctAnswer: "Disable DNS reverse resolution", explanation: "-n disables DNS reverse lookups, which can significantly speed up scans on large address ranges.", topicSlug: "target-specification", difficulty: "easy" },
  { id: 15, prompt: "What is the syntax to scan hosts .1, .5, and .10 through .20 in the 192.168.1.x range?", options: ["nmap 192.168.1.1 192.168.1.5 192.168.1.10-20", "nmap 192.168.1.[1,5,10-20]", "nmap 192.168.1.1,5,10-20", "nmap 192.168.1.1+5+10-20"], correctAnswer: "nmap 192.168.1.1,5,10-20", explanation: "Nmap supports comma-separated values and ranges within an octet: 192.168.1.1,5,10-20 scans .1, .5, and .10 through .20.", topicSlug: "target-specification", difficulty: "medium" },
  { id: 16, prompt: "How many hosts does a /8 CIDR network contain?", options: ["256", "65,536", "16,777,216", "4,294,967,296"], correctAnswer: "16,777,216", explanation: "/8 leaves 24 bits for host addresses: 2^24 = 16,777,216 addresses.", topicSlug: "target-specification", difficulty: "medium" },
  { id: 17, prompt: "What does '-iR 50' do in Nmap?", options: ["Scan 50 random ports", "Select 50 random Internet hosts as targets", "Retry each port 50 times", "Scan the top 50 ports"], correctAnswer: "Select 50 random Internet hosts as targets", explanation: "-iR <n> selects n random Internet hosts. Useful for internet-wide research but must be used ethically and legally.", topicSlug: "target-specification", difficulty: "medium" },
  { id: 18, prompt: "What does 192.168.1.* expand to in Nmap?", options: ["Only 192.168.1.0 and 192.168.1.255", "192.168.1.1 through 192.168.1.254 only", "192.168.1.0 through 192.168.1.255 (same as /24)", "All 192.168.x.x addresses"], correctAnswer: "192.168.1.0 through 192.168.1.255 (same as /24)", explanation: "The * wildcard in an octet position expands to 0-255, making 192.168.1.* equivalent to 192.168.1.0/24.", topicSlug: "target-specification", difficulty: "easy" },
  { id: 19, prompt: "Which flag enables IPv6 scanning in Nmap?", options: ["-4", "-6", "--ipv6", "-v6"], correctAnswer: "-6", explanation: "-6 enables IPv6 mode, allowing Nmap to scan IPv6 addresses and resolve AAAA DNS records.", topicSlug: "target-specification", difficulty: "medium" },
  { id: 20, prompt: "What is the purpose of --excludefile in Nmap?", options: ["Exclude specific ports from scanning", "Read a file of hosts to exclude from the scan", "Exclude certain script categories", "Skip output to file"], correctAnswer: "Read a file of hosts to exclude from the scan", explanation: "--excludefile reads exclusion targets from a file, similar to --exclude but for larger exclusion lists.", topicSlug: "target-specification", difficulty: "medium" },

  // ─── Port States (21-28) ───
  { id: 21, prompt: "What does a 'filtered' port state indicate?", options: ["An application is listening on the port", "The port is closed but accessible", "A firewall is blocking packets to the port", "The port state could not be determined"], correctAnswer: "A firewall is blocking packets to the port", explanation: "Filtered means a packet filter (firewall/ACL) is preventing Nmap from reaching the port. No RST is received, just silence or ICMP unreachable.", topicSlug: "port-states", difficulty: "easy" },
  { id: 22, prompt: "What is the difference between a 'closed' and 'filtered' port?", options: ["They are the same, both mean no service is running", "Closed: port accessible, returns RST, no service. Filtered: firewall blocks packets, no RST received", "Closed: firewall blocking. Filtered: service crashed", "Closed: UDP only. Filtered: TCP only"], correctAnswer: "Closed: port accessible, returns RST, no service. Filtered: firewall blocks packets, no RST received", explanation: "Closed ports respond with RST, the host is reachable but no service is listening. Filtered ports don't respond at all because a firewall drops packets.", topicSlug: "port-states", difficulty: "medium" },
  { id: 23, prompt: "When does Nmap report 'open|filtered' for a port?", options: ["When it receives both SYN-ACK and RST", "When open and filtered produce the same response (no response), common with UDP/FIN/NULL/XMAS", "Only during UDP scans", "When two scans give conflicting results"], correctAnswer: "When open and filtered produce the same response (no response), common with UDP/FIN/NULL/XMAS", explanation: "Open|filtered occurs when Nmap can't distinguish between open and filtered because both produce no response, common with UDP, FIN, NULL, and XMAS scan types.", topicSlug: "port-states", difficulty: "medium" },
  { id: 24, prompt: "Which scan type produces 'unfiltered' port states?", options: ["SYN scan (-sS)", "UDP scan (-sU)", "ACK scan (-sA)", "NULL scan (-sN)"], correctAnswer: "ACK scan (-sA)", explanation: "ACK scan produces 'unfiltered' when a port responds, it means the port is reachable but the ACK scan can't determine if it's open or closed.", topicSlug: "port-states", difficulty: "medium" },
  { id: 25, prompt: "What flag shows only open (and open|filtered) ports in Nmap output?", options: ["--show-open", "--only-open", "--open", "-p open"], correctAnswer: "--open", explanation: "--open filters the output to display only ports that are open or open|filtered, hiding closed and filtered ports.", topicSlug: "port-states", difficulty: "easy" },
  { id: 26, prompt: "What flag shows the reason Nmap assigned a specific port state?", options: ["--explain", "--reason", "--state-info", "-v"], correctAnswer: "--reason", explanation: "--reason adds a column showing why each port got its state (e.g., 'syn-ack' for open, 'reset' for closed, 'no-response' for filtered).", topicSlug: "port-states", difficulty: "easy" },
  { id: 27, prompt: "What response from a target causes Nmap to mark a TCP port as 'open'?", options: ["RST packet", "SYN/ACK packet", "ICMP echo reply", "No response"], correctAnswer: "SYN/ACK packet", explanation: "A SYN/ACK response indicates the target accepted the SYN probe, the port is open and a service is listening.", topicSlug: "port-states", difficulty: "easy" },
  { id: 28, prompt: "In which state can Nmap NOT determine if a port is open or closed, only seen with idle scan?", options: ["Open|filtered", "Closed|filtered", "Unfiltered", "Filtered"], correctAnswer: "Closed|filtered", explanation: "Closed|filtered only appears with idle scan (-sI) when Nmap cannot distinguish between a closed or filtered port.", topicSlug: "port-states", difficulty: "hard" },

  // ─── Host Discovery (29-38) ───
  { id: 29, prompt: "What does 'nmap -sn 192.168.1.0/24' do?", options: ["Performs a SYN scan on the subnet", "Does a ping sweep to find live hosts without port scanning", "Scans the top 24 ports", "Uses NSE scripts on the subnet"], correctAnswer: "Does a ping sweep to find live hosts without port scanning", explanation: "-sn (formerly -sP) disables port scanning, Nmap only performs host discovery to identify which hosts are online.", topicSlug: "host-discovery", difficulty: "easy" },
  { id: 30, prompt: "What does -Pn do in Nmap?", options: ["Performs only ping scans", "Skips host discovery and treats all hosts as online", "Uses only ICMP probes", "Performs a paranoid scan"], correctAnswer: "Skips host discovery and treats all hosts as online", explanation: "-Pn disables host discovery, Nmap skips the ping phase and directly port scans every target. Essential when ICMP is blocked by firewalls.", topicSlug: "host-discovery", difficulty: "easy" },
  { id: 31, prompt: "Which discovery method is automatically used on local Ethernet networks and cannot be blocked by host firewalls?", options: ["ICMP echo (-PE)", "TCP SYN probe (-PS)", "ARP ping (-PR)", "UDP probe (-PU)"], correctAnswer: "ARP ping (-PR)", explanation: "ARP requests work at Layer 2 and cannot be filtered by host-based firewalls. Nmap automatically uses ARP on local LAN segments when run as root.", topicSlug: "host-discovery", difficulty: "medium" },
  { id: 32, prompt: "What does -PS443 do?", options: ["Scan port 443 only", "Send TCP SYN probe to port 443 for host discovery", "Send TCP ACK probe to port 443", "Force SSL connection on port 443"], correctAnswer: "Send TCP SYN probe to port 443 for host discovery", explanation: "-PS[portlist] sends TCP SYN probes to specified ports for host discovery. A SYN/ACK or RST response indicates the host is up.", topicSlug: "host-discovery", difficulty: "medium" },
  { id: 33, prompt: "What ICMP probe type is used by -PE?", options: ["ICMP timestamp request", "ICMP echo request (classic ping)", "ICMP address mask request", "ICMP router discovery"], correctAnswer: "ICMP echo request (classic ping)", explanation: "-PE sends ICMP type 8 echo request (ping). It's the most basic host discovery probe but is often blocked by firewalls.", topicSlug: "host-discovery", difficulty: "easy" },
  { id: 34, prompt: "Why use -PA (TCP ACK probe) for host discovery instead of -PS?", options: ["ACK probes are faster", "Stateful firewalls allow ACK packets that appear to be established session traffic, bypassing SYN filters", "ACK probes use less bandwidth", "ACK probes work on UDP ports"], correctAnswer: "Stateful firewalls allow ACK packets that appear to be established session traffic, bypassing SYN filters", explanation: "Some firewalls drop incoming SYN packets but allow ACK packets (treating them as return traffic). -PA exploits this to confirm host availability.", topicSlug: "host-discovery", difficulty: "hard" },
  { id: 35, prompt: "What is a UDP probe (-PU) for host discovery looking for?", options: ["A UDP response from the service", "An ICMP port unreachable message, indicating the host is up", "A TCP RST in response to the UDP packet", "Any response from UDP port 40125"], correctAnswer: "An ICMP port unreachable message, indicating the host is up", explanation: "When a UDP probe hits a closed port, the host responds with ICMP port unreachable, proving the host is online. Silence means filtered.", topicSlug: "host-discovery", difficulty: "medium" },
  { id: 36, prompt: "How does combining -PE -PS80,443 -PA improve host discovery?", options: ["It makes the scan faster", "It reduces false positives", "It uses multiple probe types, improving detection against hosts that block some probe types", "It enables parallel scanning"], correctAnswer: "It uses multiple probe types, improving detection against hosts that block some probe types", explanation: "Different firewalls block different probe types. Combining ICMP, TCP SYN, and TCP ACK probes maximizes the chance of detecting a live host.", topicSlug: "host-discovery", difficulty: "medium" },
  { id: 37, prompt: "What is the main advantage of -sn for initial network reconnaissance?", options: ["It reveals all open ports quickly", "It maps the network of live hosts quickly and non-intrusively before deeper scanning", "It bypasses all firewalls", "It identifies the OS of each host"], correctAnswer: "It maps the network of live hosts quickly and non-intrusively before deeper scanning", explanation: "-sn gives you a list of online hosts quickly without generating the more detectable traffic of a full port scan.", topicSlug: "host-discovery", difficulty: "easy" },
  { id: 38, prompt: "What flag disables DNS resolution to speed up a ping sweep on a large subnet?", options: ["-n", "-d", "--no-dns", "-N"], correctAnswer: "-n", explanation: "-n disables reverse DNS lookups. On large subnets, DNS resolution can add significant time, -n is almost always used with -sn on big ranges.", topicSlug: "host-discovery", difficulty: "easy" },

  // ─── Port Selection (39-46) ───
  { id: 39, prompt: "What is the shorthand for scanning all 65535 TCP ports?", options: ["-p 0-65535", "-p-", "--all-ports", "-p full"], correctAnswer: "-p-", explanation: "-p- is shorthand for -p 1-65535, scans all 65535 TCP ports. Essential in CTFs and pen tests where services run on non-standard ports.", topicSlug: "port-selection", difficulty: "easy" },
  { id: 40, prompt: "What does -F do in Nmap?", options: ["Full port scan (all 65535)", "Fragment packets", "Fast scan: top 100 ports only", "Force SYN scan"], correctAnswer: "Fast scan: top 100 ports only", explanation: "-F (fast) reduces the default scan from 1000 ports to the top 100 most common ports, significantly speeding up reconnaissance.", topicSlug: "port-selection", difficulty: "easy" },
  { id: 41, prompt: "How do you scan only ports 22, 80, and 443?", options: ["-p 22-80-443", "-p 22,80,443", "--ports 22 80 443", "-p {22,80,443}"], correctAnswer: "-p 22,80,443", explanation: "Multiple specific ports are specified with comma separation in the -p flag: -p 22,80,443.", topicSlug: "port-selection", difficulty: "easy" },
  { id: 42, prompt: "What does --top-ports 500 do?", options: ["Scan the 500 highest-numbered ports", "Scan the 500 most commonly open ports", "Scan ports above 500", "Limit scan to 500 results"], correctAnswer: "Scan the 500 most commonly open ports", explanation: "--top-ports <n> scans the n most frequently open ports according to Nmap's frequency database. More targeted than scanning all 65535.", topicSlug: "port-selection", difficulty: "easy" },
  { id: 43, prompt: "What is the well-known port for SMB (Windows file sharing)?", options: ["139", "445", "137", "135"], correctAnswer: "445", explanation: "TCP 445 is the primary SMB port in modern Windows. TCP 139 is the older NetBIOS-based SMB port.", topicSlug: "port-selection", difficulty: "medium" },
  { id: 44, prompt: "How do you scan TCP port 80 and UDP port 53 in the same Nmap command?", options: ["-p 80,53 -sU -sS", "-p T:80,U:53 -sS -sU", "-sU -sS -p 80 -p 53", "Both A and B are correct"], correctAnswer: "Both A and B are correct", explanation: "You can combine -sS -sU with -p 80,53 (though it applies to both protocols) or use protocol-specific syntax like -p T:80,U:53.", topicSlug: "port-selection", difficulty: "hard" },
  { id: 45, prompt: "What is the default port for RDP (Remote Desktop Protocol)?", options: ["22", "3306", "3389", "5900"], correctAnswer: "3389", explanation: "TCP 3389 is the default port for Windows Remote Desktop Protocol. VNC uses 5900, MySQL uses 3306, SSH uses 22.", topicSlug: "port-selection", difficulty: "easy" },
  { id: 46, prompt: "Why should you always scan -p- in penetration tests?", options: ["It's faster than the default", "Services often run on non-standard high ports (backdoors, admin panels)", "It provides more accurate version detection", "It bypasses firewall rules"], correctAnswer: "Services often run on non-standard high ports (backdoors, admin panels)", explanation: "Administrators often move services to non-standard ports (e.g., SSH on 2222, HTTP on 8080) or attackers leave backdoors on high ports. The default top-1000 scan would miss these.", topicSlug: "port-selection", difficulty: "medium" },

  // ─── TCP Scan Types (47-56) ───
  { id: 47, prompt: "Why is SYN scan (-sS) called a 'stealth' or 'half-open' scan?", options: ["It only sends half the packets of a full scan", "The TCP handshake is never completed, Nmap sends RST after SYN/ACK, so no full connection is logged", "It uses half the bandwidth", "It scans only half the ports"], correctAnswer: "The TCP handshake is never completed, Nmap sends RST after SYN/ACK, so no full connection is logged", explanation: "After receiving a SYN/ACK (indicating an open port), Nmap sends RST to abort the connection. Most application-level logging requires a completed handshake.", topicSlug: "tcp-scan-types", difficulty: "easy" },
  { id: 48, prompt: "What response indicates a closed port in a SYN scan?", options: ["SYN/ACK", "RST", "No response", "FIN"], correctAnswer: "RST", explanation: "A TCP RST (reset) response to a SYN probe means the port is accessible but no service is listening. The host explicitly refuses the connection.", topicSlug: "tcp-scan-types", difficulty: "easy" },
  { id: 49, prompt: "What is the purpose of ACK scan (-sA)?", options: ["Find open TCP ports quickly", "Map firewall rules, determine if ports are filtered or unfiltered", "Perform anonymous port scanning", "Detect UDP services"], correctAnswer: "Map firewall rules, determine if ports are filtered or unfiltered", explanation: "ACK scan doesn't find open ports, it determines which ports are reachable through the firewall. All open and closed ports return RST; filtered ports don't respond.", topicSlug: "tcp-scan-types", difficulty: "medium" },
  { id: 50, prompt: "What TCP flags does an XMAS scan set?", options: ["SYN and ACK", "FIN and RST", "FIN, PSH, and URG", "SYN, FIN, and URG"], correctAnswer: "FIN, PSH, and URG", explanation: "XMAS scan sets FIN, PSH, and URG flags simultaneously, the packet 'lights up like a Christmas tree.'", topicSlug: "tcp-scan-types", difficulty: "medium" },
  { id: 51, prompt: "Why don't NULL/FIN/XMAS scans work reliably on Windows hosts?", options: ["Windows firewalls block all three", "Windows ignores packets with unexpected flag combinations instead of responding per RFC 793", "Windows uses a different port numbering scheme", "These scans require IPv6"], correctAnswer: "Windows ignores packets with unexpected flag combinations instead of responding per RFC 793", explanation: "RFC 793 says closed ports should respond to FIN/NULL/XMAS with RST, but Windows ignores these packets, making all ports appear open or filtered.", topicSlug: "tcp-scan-types", difficulty: "medium" },
  { id: 52, prompt: "What is the main advantage of NULL/FIN/XMAS scans?", options: ["They are faster than SYN scans", "They can bypass some non-stateful packet filters and older IDSes that only watch for SYN packets", "They work without a network connection", "They provide more accurate version detection"], correctAnswer: "They can bypass some non-stateful packet filters and older IDSes that only watch for SYN packets", explanation: "Non-stateful firewalls and older IDSes often only monitor for SYN packets. NULL/FIN/XMAS probes may pass through undetected.", topicSlug: "tcp-scan-types", difficulty: "medium" },
  { id: 53, prompt: "What sets TCP Connect scan (-sT) apart from SYN scan (-sS)?", options: ["Connect scan is faster", "Connect scan completes the full three-way handshake using the OS connect() syscall, doesn't require root", "Connect scan uses fewer packets", "Connect scan works on UDP"], correctAnswer: "Connect scan completes the full three-way handshake using the OS connect() syscall, doesn't require root", explanation: "-sT uses the OS's standard network API, no raw packet access needed. However, completed connections are more likely to be logged by the target.", topicSlug: "tcp-scan-types", difficulty: "easy" },
  { id: 54, prompt: "A NULL scan sends a TCP packet with which flags?", options: ["No flags set", "Only the FIN flag", "FIN and PSH", "SYN only"], correctAnswer: "No flags set", explanation: "NULL scan (-sN) sends a TCP segment with no flags set. Per RFC 793, closed ports respond with RST; open ports silently drop the packet.", topicSlug: "tcp-scan-types", difficulty: "easy" },
  { id: 55, prompt: "What response from a closed port differentiates NULL/FIN/XMAS scans from SYN scan?", options: ["SYN/ACK", "RST, same in all scan types for closed ports", "ICMP unreachable", "FIN/ACK"], correctAnswer: "RST, same in all scan types for closed ports", explanation: "In NULL/FIN/XMAS scans, closed ports still return RST, this is how Nmap determines they are closed. Open ports silently drop the unusual packets.", topicSlug: "tcp-scan-types", difficulty: "medium" },
  { id: 56, prompt: "When would you choose -sT over -sS?", options: ["When you need faster results", "When you don't have root privileges or when scanning through a SOCKS proxy", "When scanning UDP ports", "When the target is running Windows"], correctAnswer: "When you don't have root privileges or when scanning through a SOCKS proxy", explanation: "-sT is necessary when raw socket access isn't available (no root) or when routing through proxies, since proxies forward TCP connections, not raw packets.", topicSlug: "tcp-scan-types", difficulty: "medium" },

  // ─── UDP Scanning (57-64) ───
  { id: 57, prompt: "What flag enables UDP scanning in Nmap?", options: ["-sU", "-U", "--udp", "-u"], correctAnswer: "-sU", explanation: "-sU enables UDP scan mode. It can be combined with TCP scans (e.g., -sS -sU) for comprehensive coverage.", topicSlug: "udp-scanning", difficulty: "easy" },
  { id: 58, prompt: "Why is UDP scanning much slower than TCP scanning?", options: ["UDP packets are larger", "UDP is connectionless, no response means open|filtered, requiring Nmap to wait for timeouts and respecting rate limits", "UDP requires authentication", "Nmap sends more probes per port for UDP"], correctAnswer: "UDP is connectionless, no response means open|filtered, requiring Nmap to wait for timeouts and respecting rate limits", explanation: "Without a three-way handshake, Nmap can't confirm open ports from silence. The Linux kernel also rate-limits ICMP unreachable responses to ~1/second.", topicSlug: "udp-scanning", difficulty: "medium" },
  { id: 59, prompt: "What response indicates a closed UDP port?", options: ["UDP response from the service", "ICMP port unreachable (type 3, code 3)", "No response (timeout)", "TCP RST packet"], correctAnswer: "ICMP port unreachable (type 3, code 3)", explanation: "When a UDP probe hits a closed port, the host generates an ICMP port unreachable message. This is the definitive indicator of a closed UDP port.", topicSlug: "udp-scanning", difficulty: "medium" },
  { id: 60, prompt: "Why is SNMP (UDP 161) a high-priority target in UDP scans?", options: ["It's the most commonly open UDP port", "It can expose extensive system information if default community strings (public/private) are used", "It's required for network routing", "It enables remote code execution by default"], correctAnswer: "It can expose extensive system information if default community strings (public/private) are used", explanation: "SNMP with default community strings ('public', 'private') can reveal system info, running processes, interfaces, routing tables, and sometimes allow configuration changes.", topicSlug: "udp-scanning", difficulty: "medium" },
  { id: 61, prompt: "What does 'open|filtered' mean for a UDP port?", options: ["The port has both TCP and UDP open", "Nmap can't determine if it's open or filtered, both result in no response", "The port was open but is now filtered", "Both services are running simultaneously"], correctAnswer: "Nmap can't determine if it's open or filtered, both result in no response", explanation: "For UDP, if a port is open the service may silently drop the generic probe. If filtered, the firewall drops it. Either way = no response = open|filtered.", topicSlug: "udp-scanning", difficulty: "medium" },
  { id: 62, prompt: "Which flag quickly limits a UDP scan to the most important ports?", options: ["--top-ports 20", "-p 1-100", "-F", "-T5"], correctAnswer: "--top-ports 20", explanation: "--top-ports 20 scans the 20 most commonly open UDP ports (DNS 53, DHCP 67/68, SNMP 161, etc.), much faster than a full UDP scan.", topicSlug: "udp-scanning", difficulty: "easy" },
  { id: 63, prompt: "What is the default port used by NTP that is important to include in UDP scans?", options: ["161", "53", "123", "514"], correctAnswer: "123", explanation: "NTP (Network Time Protocol) uses UDP 123. NTP amplification is a common DDoS vector; misconfigured NTP servers can leak internal network info.", topicSlug: "udp-scanning", difficulty: "medium" },
  { id: 64, prompt: "How do you combine a TCP SYN scan and UDP scan in one Nmap command?", options: ["-sS + -sU (use both flags)", "-sSU (combined shorthand)", "nmap --dual-scan", "Both -sS and -sU flags together work"], correctAnswer: "Both -sS and -sU flags together work", explanation: "Running sudo nmap -sS -sU [target] performs both a TCP SYN scan and UDP scan simultaneously, providing comprehensive coverage in one pass.", topicSlug: "udp-scanning", difficulty: "easy" },

  // ─── Service & Version Detection (65-72) ───
  { id: 65, prompt: "What flag enables service and version detection in Nmap?", options: ["-V", "-sV", "--version", "-v"], correctAnswer: "-sV", explanation: "-sV probes open ports and matches responses against the nmap-service-probes database to identify service names and versions.", topicSlug: "service-version-detection", difficulty: "easy" },
  { id: 66, prompt: "What is the default version intensity level for -sV?", options: ["1", "3", "5", "9"], correctAnswer: "5", explanation: "The default version intensity is 5 (on a scale of 0-9). Higher intensity sends more probes and takes longer but is more thorough.", topicSlug: "service-version-detection", difficulty: "medium" },
  { id: 67, prompt: "What does --version-intensity 9 do?", options: ["Scan 9 additional ports for version info", "Try all available service probes, most thorough but slowest", "Enable all 9 version detection protocols", "Version intensity 9 is not valid"], correctAnswer: "Try all available service probes, most thorough but slowest", explanation: "--version-intensity 9 (or --version-all) tries every probe in nmap-service-probes, maximizing detection accuracy at the cost of speed.", topicSlug: "service-version-detection", difficulty: "medium" },
  { id: 68, prompt: "What is a CPE string in Nmap version detection output?", options: ["Connection Protocol Enumeration, tracks active connections", "Common Platform Enumeration, standardized identifier for software like cpe:/a:apache:http_server:2.4.50", "Certificate Public Exchange, TLS certificate format", "Custom Port Enumeration, user-defined port labels"], correctAnswer: "Common Platform Enumeration, standardized identifier for software like cpe:/a:apache:http_server:2.4.50", explanation: "CPE strings provide a standardized way to identify software and can be used to query vulnerability databases like NVD to find CVEs.", topicSlug: "service-version-detection", difficulty: "medium" },
  { id: 69, prompt: "What is banner grabbing in the context of Nmap version detection?", options: ["Collecting web page titles", "Capturing the text a service sends upon connection, which often reveals software name and version", "Downloading service documentation", "Extracting authentication headers"], correctAnswer: "Capturing the text a service sends upon connection, which often reveals software name and version", explanation: "Many services send an identifying banner when a client connects. Version detection captures these banners as part of fingerprinting.", topicSlug: "service-version-detection", difficulty: "easy" },
  { id: 70, prompt: "What does --version-light do?", options: ["Only detect version for HTTP services", "Use version intensity 2, lighter, faster version detection", "Show version in light/simplified format", "Disable version detection"], correctAnswer: "Use version intensity 2, lighter, faster version detection", explanation: "--version-light is equivalent to --version-intensity 2. It uses fewer probes for faster (but less complete) version detection.", topicSlug: "service-version-detection", difficulty: "medium" },
  { id: 71, prompt: "Why is version detection (-sV) critical in penetration testing?", options: ["It's required by Nmap to work", "Exact version numbers can be directly mapped to known CVEs and exploits", "It speeds up port scanning", "It enables OS detection"], correctAnswer: "Exact version numbers can be directly mapped to known CVEs and exploits", explanation: "Knowing that a service is 'OpenSSH 7.4' vs '8.2' can immediately indicate known vulnerabilities. Version info feeds directly into vulnerability assessment.", topicSlug: "service-version-detection", difficulty: "easy" },
  { id: 72, prompt: "What four capabilities does -A (aggressive scan) combine?", options: ["UDP + TCP + ICMP + ARP scans", "OS detection + version detection + default scripts + traceroute", "Version + NSE + evasion + timing", "All scan types running in parallel"], correctAnswer: "OS detection + version detection + default scripts + traceroute", explanation: "-A combines -O (OS), -sV (version), -sC (default scripts), and --traceroute in a single convenient flag.", topicSlug: "service-version-detection", difficulty: "easy" },

  // ─── OS Detection (73-80) ───
  { id: 73, prompt: "What flag enables OS detection in Nmap?", options: ["-O", "--os-detect", "-sO", "--fingerprint"], correctAnswer: "-O", explanation: "-O enables OS detection, which analyzes TCP/IP stack characteristics to identify the target's operating system and version.", topicSlug: "os-detection", difficulty: "easy" },
  { id: 74, prompt: "What does Nmap need to perform accurate OS detection?", options: ["Only root privileges", "At least one open and one closed TCP port, plus root privileges", "A specific target OS version", "The target's MAC address"], correctAnswer: "At least one open and one closed TCP port, plus root privileges", explanation: "OS detection sends probes to both an open and closed port to generate diverse responses. Without both, fingerprinting is inaccurate.", topicSlug: "os-detection", difficulty: "medium" },
  { id: 75, prompt: "What does --osscan-guess do?", options: ["Skips OS detection for efficiency", "Forces Nmap to report its best OS guess even at low confidence", "Randomly selects between OS candidates", "Uses only TCP probes for OS detection"], correctAnswer: "Forces Nmap to report its best OS guess even at low confidence", explanation: "--osscan-guess (or --fuzzy) makes Nmap report the closest matching OS fingerprint even when the confidence percentage is below the normal threshold.", topicSlug: "os-detection", difficulty: "medium" },
  { id: 76, prompt: "Why might OS detection give inaccurate results behind a NAT device?", options: ["NAT uses a different OS than the hosts behind it", "NAT devices modify packet headers, making all hosts look similar at the TCP/IP level", "NAT blocks OS detection probes entirely", "NAT only supports IPv6"], correctAnswer: "NAT devices modify packet headers, making all hosts look similar at the TCP/IP level", explanation: "NAT modifies source IPs, TTL values, and sometimes TCP options. The scanner sees the NAT device's TCP/IP characteristics, not the actual hosts.", topicSlug: "os-detection", difficulty: "medium" },
  { id: 77, prompt: "What aspects of the TCP/IP stack does Nmap analyze for OS fingerprinting?", options: ["Only TTL values", "TCP ISN patterns, TCP options ordering, ICMP responses, TTL, and window sizes", "Only the MAC address OUI", "Port numbers and service banners"], correctAnswer: "TCP ISN patterns, TCP options ordering, ICMP responses, TTL, and window sizes", explanation: "Nmap's OS fingerprinting sends ~13 probes and analyzes TCP sequence numbers, options, ICMP behavior, IP TTL, and TCP window size, all OS-specific characteristics.", topicSlug: "os-detection", difficulty: "hard" },
  { id: 78, prompt: "What does --osscan-limit do?", options: ["Limits OS detection to 5 guesses", "Skips OS detection on hosts without both an open and closed port (speeds up large scans)", "Limits OS detection to Windows hosts only", "Restricts OS detection accuracy"], correctAnswer: "Skips OS detection on hosts without both an open and closed port (speeds up large scans)", explanation: "--osscan-limit prevents Nmap from wasting time attempting OS detection on hosts that can't yield accurate results anyway.", topicSlug: "os-detection", difficulty: "medium" },
  { id: 79, prompt: "How does virtualization affect OS detection?", options: ["It has no effect", "VMs may show the hypervisor's TCP/IP characteristics, causing Nmap to fingerprint the host OS", "VMs always show as Linux", "OS detection doesn't work in virtual environments"], correctAnswer: "VMs may show the hypervisor's TCP/IP characteristics, causing Nmap to fingerprint the host OS", explanation: "Virtual machines running on a hypervisor can expose TCP/IP fingerprints that reflect the hypervisor or blend with its characteristics, causing inaccurate OS guesses.", topicSlug: "os-detection", difficulty: "medium" },
  { id: 80, prompt: "What confidence percentage is generally considered reliable in Nmap OS detection?", options: ["50%+", "75%+", "96%+", "100% only"], correctAnswer: "96%+", explanation: "A confidence level of 96% or higher indicates a reliable OS match. Below this, Nmap will list multiple candidates and the result should be treated as a hint.", topicSlug: "os-detection", difficulty: "medium" },

  // ─── NSE Scripting Engine (81-89) ───
  { id: 81, prompt: "What flag runs default NSE scripts in Nmap?", options: ["--scripts", "-sC", "--nse", "-N"], correctAnswer: "-sC", explanation: "-sC (or --script=default) runs scripts in the 'default' category, these are safe, useful scripts unlikely to crash services.", topicSlug: "nse-basics", difficulty: "easy" },
  { id: 82, prompt: "What language are Nmap NSE scripts written in?", options: ["Python", "JavaScript", "Lua", "Perl"], correctAnswer: "Lua", explanation: "All NSE scripts are written in Lua, a fast, lightweight embedded scripting language.", topicSlug: "nse-basics", difficulty: "easy" },
  { id: 83, prompt: "Which NSE script category actively exploits vulnerabilities?", options: ["default", "discovery", "exploit", "intrusive"], correctAnswer: "exploit", explanation: "The 'exploit' category contains scripts that actively attempt to exploit vulnerabilities. Use only with explicit permission, they can cause damage.", topicSlug: "nse-basics", difficulty: "medium" },
  { id: 84, prompt: "What command checks for known vulnerabilities using NSE?", options: ["nmap --script=vuln target", "nmap -sV --cve target", "nmap --vulnerabilities target", "nmap -V target"], correctAnswer: "nmap --script=vuln target", explanation: "--script=vuln runs all scripts in the 'vuln' category, checking for known vulnerabilities across discovered services.", topicSlug: "nse-basics", difficulty: "easy" },
  { id: 85, prompt: "Where are NSE scripts stored on Linux systems?", options: ["/etc/nmap/scripts/", "/usr/share/nmap/scripts/", "/opt/nmap/scripts/", "/var/lib/nmap/"], correctAnswer: "/usr/share/nmap/scripts/", explanation: "Nmap installs scripts in /usr/share/nmap/scripts/ on Linux. Use 'nmap --script-updatedb' after adding custom scripts to update the script database.", topicSlug: "nse-basics", difficulty: "medium" },
  { id: 86, prompt: "How do you run all http-* scripts against a target?", options: ["nmap --script=http 192.168.1.1", "nmap --script=http-* 192.168.1.1", "nmap --http-scripts 192.168.1.1", "nmap -sC=http 192.168.1.1"], correctAnswer: "nmap --script=http-* 192.168.1.1", explanation: "NSE supports wildcard patterns. --script=http-* runs all scripts whose names start with 'http-'.", topicSlug: "nse-basics", difficulty: "medium" },
  { id: 87, prompt: "Which NSE script category is safest to run during authorized scans?", options: ["exploit", "dos", "default", "brute"], correctAnswer: "default", explanation: "The 'default' category is designed to be safe and non-intrusive, it won't crash services or trigger aggressive alerts, making it ideal for initial enumeration.", topicSlug: "nse-basics", difficulty: "easy" },
  { id: 88, prompt: "What NSE script checks for anonymous FTP access?", options: ["ftp-open", "ftp-anonymous", "ftp-anon", "ftp-check"], correctAnswer: "ftp-anon", explanation: "The ftp-anon script checks if an FTP server allows anonymous login, a common misconfiguration that can expose sensitive files.", topicSlug: "nse-basics", difficulty: "medium" },
  { id: 89, prompt: "How do you pass arguments to an NSE script?", options: ["--script-flags key=value", "--script-args key=value", "--nse-args key=value", "--script-options key=value"], correctAnswer: "--script-args key=value", explanation: "--script-args passes key=value pairs to scripts. Example: --script=ssh-brute --script-args userdb=users.txt,passdb=pass.txt", topicSlug: "nse-basics", difficulty: "medium" },

  // ─── Timing & Performance (90-97) ───
  { id: 90, prompt: "What timing template is recommended for most penetration tests on reliable networks?", options: ["-T1", "-T2", "-T3", "-T4"], correctAnswer: "-T4", explanation: "-T4 (Aggressive) is the de facto standard for pen tests on LANs and fast internet connections, fast enough to be efficient, not so fast as to miss results.", topicSlug: "timing-performance", difficulty: "easy" },
  { id: 91, prompt: "What is the slowest timing template and why would you use it?", options: ["-T0 (Paranoid), sends one packet every 5 minutes to evade IDS threshold detection", "-T1 (Sneaky), one packet per 15 seconds to hide in traffic", "-T5 (Insane), sends packets so fast they look like noise", "-T2 (Polite), minimizes bandwidth impact"], correctAnswer: "-T0 (Paranoid), sends one packet every 5 minutes to evade IDS threshold detection", explanation: "-T0 (Paranoid) is used when maximum stealth is required against threshold-based IDS systems. Practically, modern behavioral IDS can still detect it.", topicSlug: "timing-performance", difficulty: "easy" },
  { id: 92, prompt: "What does --min-rate 1000 do?", options: ["Wait at least 1000ms between packets", "Send at least 1000 packets per second", "Scan with at minimum 1000 parallel threads", "Minimum 1000 retries per port"], correctAnswer: "Send at least 1000 packets per second", explanation: "--min-rate <n> enforces a minimum packet send rate. Useful with -p- full port scans to ensure they complete in reasonable time.", topicSlug: "timing-performance", difficulty: "medium" },
  { id: 93, prompt: "What is the default timing template (-T3) called?", options: ["Slow", "Normal", "Polite", "Default"], correctAnswer: "Normal", explanation: "-T3 is named 'Normal' and is the default timing template, balanced between speed and reliability for typical networks.", topicSlug: "timing-performance", difficulty: "easy" },
  { id: 94, prompt: "What does --max-retries 2 do?", options: ["Retry failed hosts 2 times", "Limit probe retransmissions to 2, reduces scan time at the cost of potentially missing some results", "Scan each port exactly 2 times", "Set maximum to 2 parallel threads"], correctAnswer: "Limit probe retransmissions to 2, reduces scan time at the cost of potentially missing some results", explanation: "--max-retries limits how many times Nmap resends a probe that received no response. Lower values speed up scans but may miss filtered ports.", topicSlug: "timing-performance", difficulty: "medium" },
  { id: 95, prompt: "Why should you avoid -T5 in production environments?", options: ["It doesn't work in production", "It may saturate network links, miss open ports, and crash services due to extreme packet rates", "It requires a license", "It only works on local networks"], correctAnswer: "It may saturate network links, miss open ports, and crash services due to extreme packet rates", explanation: "-T5 (Insane) sends packets as fast as possible. This can overwhelm network devices, trigger DoS conditions, and paradoxically cause more missed results.", topicSlug: "timing-performance", difficulty: "medium" },
  { id: 96, prompt: "What is the recommended command pattern for a fast full-port scan?", options: ["nmap -T5 -p- target", "nmap -p- -T4 --min-rate 5000 target", "nmap -F -T2 target", "nmap -p- --slow target"], correctAnswer: "nmap -p- -T4 --min-rate 5000 target", explanation: "-p- scans all ports, -T4 provides aggressive timing, and --min-rate 5000 ensures the scan completes quickly. This is the standard CTF/pentest full-port scan command.", topicSlug: "timing-performance", difficulty: "medium" },
  { id: 97, prompt: "What does --stats-every 30s do during a scan?", options: ["Sends statistics to a remote server every 30 seconds", "Prints scan progress and statistics to the terminal every 30 seconds", "Stops and saves scan data every 30 seconds", "Limits scan to 30-second intervals"], correctAnswer: "Prints scan progress and statistics to the terminal every 30 seconds", explanation: "--stats-every <interval> shows a progress report at regular intervals, useful during long full-port scans to know how far along you are.", topicSlug: "timing-performance", difficulty: "easy" },

  // ─── Output Formats (98-104) ───
  { id: 98, prompt: "What flag saves all three output formats simultaneously?", options: ["-oA", "-oAll", "--all-output", "-o*"], correctAnswer: "-oA", explanation: "-oA <basename> saves normal (.nmap), XML (.xml), and grepable (.gnmap) output simultaneously from a single scan.", topicSlug: "output-formats", difficulty: "easy" },
  { id: 99, prompt: "Which output format is best for importing results into Metasploit or other security tools?", options: ["Normal (-oN)", "Grepable (-oG)", "XML (-oX)", "Script kiddie (-oS)"], correctAnswer: "XML (-oX)", explanation: "XML is machine-parseable and directly supported by security platforms like Metasploit, Faraday, and vulnerability management tools.", topicSlug: "output-formats", difficulty: "easy" },
  { id: 100, prompt: "What file extension does Nmap grepable output use when saved with -oA?", options: [".grep", ".gnmap", ".gmap", ".txt"], correctAnswer: ".gnmap", explanation: "When using -oA, the grepable output gets the .gnmap extension. The three files created are .nmap, .xml, and .gnmap.", topicSlug: "output-formats", difficulty: "medium" },
  { id: 101, prompt: "What is grepable output (-oG) useful for?", options: ["Importing into vulnerability scanners", "Processing with grep/awk/cut to extract specific data like all hosts with port 22 open", "Human-readable reports", "Real-time monitoring"], correctAnswer: "Processing with grep/awk/cut to extract specific data like all hosts with port 22 open", explanation: "Grepable format puts each host on one line, making it easy to use: grep '22/open' scan.gnmap | awk '{print $2}'", topicSlug: "output-formats", difficulty: "medium" },
  { id: 102, prompt: "What does -v (verbose) do during a scan?", options: ["Increases version detection intensity", "Shows discovered open ports and scan progress in real-time rather than waiting for scan completion", "Enables verbose output format", "Verifies scan results twice"], correctAnswer: "Shows discovered open ports and scan progress in real-time rather than waiting for scan completion", explanation: "-v prints results as they're discovered, so you don't have to wait for the full scan to complete before seeing open ports.", topicSlug: "output-formats", difficulty: "easy" },
  { id: 103, prompt: "What does -d (debug) do in Nmap?", options: ["Disable host discovery", "Show extremely detailed debugging information about scan internals", "Perform deep packet inspection", "Use DNS for host lookup"], correctAnswer: "Show extremely detailed debugging information about scan internals", explanation: "-d (and -dd for more) enables debug mode, printing internal Nmap details useful for troubleshooting scan issues.", topicSlug: "output-formats", difficulty: "medium" },
  { id: 104, prompt: "What flag shows all packets sent and received during a scan?", options: ["--verbose-packets", "--packet-trace", "--show-packets", "-P"], correctAnswer: "--packet-trace", explanation: "--packet-trace displays every packet sent and received, including timing and flags, essential for deep scan debugging.", topicSlug: "output-formats", difficulty: "medium" },

  // ─── Firewall/IDS Evasion (105-114) ───
  { id: 105, prompt: "What does the -f flag do in Nmap?", options: ["Enable fast scan mode", "Fragment IP packets into 8-byte chunks to bypass packet filters", "Force TCP connection", "Filter output results"], correctAnswer: "Fragment IP packets into 8-byte chunks to bypass packet filters", explanation: "-f splits TCP/IP packets into 8-byte fragments. Many older packet filters can't reassemble fragments before applying rules, allowing probes to slip through.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 106, prompt: "What does a decoy scan (-D RND:10) do?", options: ["Scan 10 random ports using decoy methods", "Generate 10 random decoy IP addresses that appear to scan alongside you, obscuring the real source", "Use 10 different scan types in parallel", "Randomize the first 10 packets sent"], correctAnswer: "Generate 10 random decoy IP addresses that appear to scan alongside you, obscuring the real source", explanation: "-D RND:10 creates 10 random decoy IPs. The target sees scan traffic from 11 sources simultaneously and can't easily identify which is real.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 107, prompt: "Why does --source-port 53 help bypass some firewalls?", options: ["DNS traffic on port 53 is encrypted and can't be inspected", "Some firewall ACLs allow traffic from source port 53 assuming it is DNS reply traffic", "Port 53 bypasses all IDS systems", "DNS packets are fragmented by default"], correctAnswer: "Some firewall ACLs allow traffic from source port 53 assuming it is DNS reply traffic", explanation: "Many firewalls have rules allowing inbound traffic with source port 53 (trusting it as DNS responses). --source-port 53 exploits this misconfiguration.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 108, prompt: "What is an idle scan (-sI) and what makes it unique?", options: ["A very slow scan using -T0", "A scan using a zombie host, the target never sees the real scanner's IP address", "A scan that only runs when the network is idle", "An idle scan uses minimal CPU resources"], correctAnswer: "A scan using a zombie host, the target never sees the real scanner's IP address", explanation: "-sI uses a 'zombie' host with predictable IP ID increments to scan the target. The target's RST responses go to the zombie, and Nmap infers port states from IP ID changes.", topicSlug: "firewall-evasion", difficulty: "hard" },
  { id: 109, prompt: "What does --data-length 24 do in an evasion context?", options: ["Limit scan to 24 packets", "Append 24 random bytes to packets, disguising them from IDS signatures for typical Nmap probes", "Set maximum data length in responses", "Send 24-byte MTU fragments"], correctAnswer: "Append 24 random bytes to packets, disguising them from IDS signatures for typical Nmap probes", explanation: "Nmap probes are normally small; --data-length adds padding to make them appear more like normal traffic and avoid signature-based detection.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 110, prompt: "What does --spoof-mac 0 do?", options: ["Disable MAC address recording", "Use a randomly generated source MAC address", "Set MAC to all zeros (00:00:00:00:00:00)", "Spoof the target's MAC address"], correctAnswer: "Use a randomly generated source MAC address", explanation: "--spoof-mac 0 generates a random MAC address for the source. Only effective on local Ethernet segments since MACs don't traverse routers.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 111, prompt: "What is the key requirement for a zombie host in an idle scan?", options: ["It must be running a web server", "It must have predictable IP ID increments (incrementing by 1 for each packet sent)", "It must be on the same subnet as the target", "It must have root access"], correctAnswer: "It must have predictable IP ID increments (incrementing by 1 for each packet sent)", explanation: "Idle scan works by measuring IP ID changes in the zombie's traffic. If the zombie's IP ID increments are random, the technique fails.", topicSlug: "firewall-evasion", difficulty: "hard" },
  { id: 112, prompt: "How does packet fragmentation (-f) help evade firewalls?", options: ["Fragmented packets travel faster through firewalls", "Many older/simpler firewalls can't reassemble fragments before applying rules, so the probe passes uninspected", "Fragmentation encrypts the packet payload", "Firewalls skip fragmented packets by default"], correctAnswer: "Many older/simpler firewalls can't reassemble fragments before applying rules, so the probe passes uninspected", explanation: "Stateless or older firewalls apply rules to individual fragments without reassembling them first. Fragmentation can split the TCP header across packets, bypassing the filter.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 113, prompt: "What does 'ME' represent in a decoy scan (-D 10.0.0.1,ME,10.0.0.3)?", options: ["Master Entity, the controller host", "The real scanning machine's IP address", "A middle proxy host", "Message Encapsulation header"], correctAnswer: "The real scanning machine's IP address", explanation: "ME in a decoy list represents the actual scanner's IP. Placing ME among decoys gives the target multiple scan sources to investigate, making attribution harder.", topicSlug: "firewall-evasion", difficulty: "medium" },
  { id: 114, prompt: "Which evasion technique routes Nmap traffic through proxy servers?", options: ["--proxies", "--tunnel", "--relay", "--bounce"], correctAnswer: "--proxies", explanation: "--proxies accepts a comma-separated list of HTTP or SOCKS4 proxy URLs and routes scan traffic through them, helping obscure the true scanner location.", topicSlug: "firewall-evasion", difficulty: "medium" },
];
