export type UnixSecurityQuestion = {
  id: number;
  prompt: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  topicSlug: string;
  difficulty: "easy" | "medium" | "hard";
};

export const UNIX_SECURITY_QUESTIONS: UnixSecurityQuestion[] = [
  // terminal-basics
  { id: 1, prompt: "What does the whoami command print?", options: ["The current directory", "Your current username", "All logged-in users", "Your IP address"], correctAnswer: "Your current username", explanation: "whoami prints the username of the user currently running the command. Simple but essential for confirming your identity in a shell session.", topicSlug: "terminal-basics", difficulty: "easy" },
  { id: 2, prompt: "Which ls flag shows hidden files?", options: ["-l", "-h", "-a", "-r"], correctAnswer: "-a", explanation: "Hidden files on Unix start with a dot. The -a flag (all) includes them in the listing. Without it, ls silently skips anything starting with a dot.", topicSlug: "terminal-basics", difficulty: "easy" },
  { id: 3, prompt: "What does the pipe character | do?", options: ["Redirects output to a file", "Sends output from one command as input to another", "Runs two commands in parallel", "Shows the command history"], correctAnswer: "Sends output from one command as input to another", explanation: "The pipe chains commands together. ps aux | grep python sends ps output directly into grep instead of printing it to the screen.", topicSlug: "terminal-basics", difficulty: "easy" },
  { id: 4, prompt: "What does grep -v do?", options: ["Case-insensitive match", "Invert match: show lines that do NOT contain the pattern", "Count matching lines", "Recursive search"], correctAnswer: "Invert match: show lines that do NOT contain the pattern", explanation: "-v inverts the match. grep -v com.apple shows every line that does not contain 'com.apple', useful for filtering out known-good entries.", topicSlug: "terminal-basics", difficulty: "easy" },
  { id: 5, prompt: "What does sudo do?", options: ["Switches to a different user permanently", "Runs a command as root after password confirmation", "Shows the superuser directory", "Disables user restrictions"], correctAnswer: "Runs a command as root after password confirmation", explanation: "sudo (Super User Do) executes the following command with root privileges. The system asks for your password to confirm you are authorizing the action.", topicSlug: "terminal-basics", difficulty: "easy" },
  { id: 6, prompt: "In ls -l output, what does the first character 'l' indicate?", options: ["Locked file", "Large file", "Symbolic link", "Log file"], correctAnswer: "Symbolic link", explanation: "The first character shows the file type. l = symbolic link, d = directory, - = regular file, p = named pipe.", topicSlug: "terminal-basics", difficulty: "medium" },
  { id: 7, prompt: "Why should you use ls -la when investigating suspicious files?", options: ["It shows file sizes in megabytes", "It shows hidden files and detailed ownership/permissions", "It sorts by modification time", "It shows file checksums"], correctAnswer: "It shows hidden files and detailed ownership/permissions", explanation: "-l gives long format (permissions, owner, size, date) and -a shows hidden files. Hidden dotfiles are a common hiding place for malware artifacts.", topicSlug: "terminal-basics", difficulty: "medium" },
  { id: 8, prompt: "A process is running as root but you did not start it. What should you do?", options: ["Ignore it since root processes are always legitimate", "Investigate the process name, PID, and what it is doing", "Restart the computer immediately", "Delete the process binary"], correctAnswer: "Investigate the process name, PID, and what it is doing", explanation: "Unexpected root processes are worth investigating. Use ps aux to get details, lsof -p PID to see what it has open, and check logs for when it started.", topicSlug: "terminal-basics", difficulty: "medium" },

  // processes-deep-dive
  { id: 9, prompt: "What does ps aux show?", options: ["Only your own processes", "Only processes using high CPU", "Every running process from all users", "Only system processes"], correctAnswer: "Every running process from all users", explanation: "ps aux shows all processes (a = all users, u = user-oriented format, x = include processes without a terminal). It is the most complete process snapshot.", topicSlug: "processes-deep-dive", difficulty: "easy" },
  { id: 10, prompt: "What is the difference between kill and kill -9?", options: ["They are identical", "kill -9 is slower", "kill sends SIGTERM (can be ignored), kill -9 sends SIGKILL (cannot be ignored)", "kill requires root, kill -9 does not"], correctAnswer: "kill sends SIGTERM (can be ignored), kill -9 sends SIGKILL (cannot be ignored)", explanation: "SIGTERM gives the process a chance to clean up. SIGKILL forces immediate termination. Always try SIGTERM first; use -9 only when the process refuses to stop.", topicSlug: "processes-deep-dive", difficulty: "easy" },
  { id: 11, prompt: "Why is a process running from /tmp suspicious?", options: ["Because /tmp is encrypted", "Because /tmp requires root to write", "Because legitimate software does not install to /tmp", "Because /tmp is not in the PATH"], correctAnswer: "Because legitimate software does not install to /tmp", explanation: "/tmp is world-writable and cleared on reboot. Malware is often dropped there because any user can write files there without special permissions. Legitimate apps install to /usr, /Applications, etc.", topicSlug: "processes-deep-dive", difficulty: "medium" },
  { id: 12, prompt: "How do you see processes not owned by root or your own user?", options: ["ps -u root", "ps aux | grep -v root | grep -v $(whoami)", "ps aux | grep unknown", "top -o user"], correctAnswer: "ps aux | grep -v root | grep -v $(whoami)", explanation: "Chaining two grep -v filters removes root's processes and your own, leaving service accounts and other users. Unexpected entries here are worth investigating.", topicSlug: "processes-deep-dive", difficulty: "medium" },
  { id: 13, prompt: "What does pkill -f do compared to kill?", options: ["pkill kills by port number", "pkill kills by process name pattern without needing the PID", "pkill only kills root processes", "pkill sends a different signal than kill"], correctAnswer: "pkill kills by process name pattern without needing the PID", explanation: "pkill -f matches against the full command line. Useful when you know the script or program name but not its PID. kill requires the exact PID.", topicSlug: "processes-deep-dive", difficulty: "medium" },
  { id: 14, prompt: "Which command gives a live updating view of the most active processes?", options: ["ps aux", "pstree", "top", "watch ps"], correctAnswer: "top", explanation: "top refreshes in real time (usually every few seconds) showing current CPU and memory usage. Press q to quit, or on macOS use top -o cpu to sort by CPU.", topicSlug: "processes-deep-dive", difficulty: "easy" },
  { id: 15, prompt: "A process has a randomly generated name like 'xf3k9z2'. What is the most likely explanation?", options: ["It is a system optimization process", "It is a compressed archive", "It may be malware using a random name to avoid detection", "It is a temporary compiler artifact"], correctAnswer: "It may be malware using a random name to avoid detection", explanation: "Legitimate software has readable names. Random character strings as process names are a common obfuscation technique used by malware to avoid simple name-based detection.", topicSlug: "processes-deep-dive", difficulty: "medium" },
  { id: 16, prompt: "What does ps aux | sort -k3 -rn | head -10 show you?", options: ["The 10 oldest processes", "The 10 processes using the most memory", "The 10 processes using the most CPU", "The 10 most recently started processes"], correctAnswer: "The 10 processes using the most CPU", explanation: "sort -k3 sorts by column 3 (%CPU in ps aux output), -r reverses to descending, -n sorts numerically. head -10 shows only the top 10.", topicSlug: "processes-deep-dive", difficulty: "hard" },

  // filesystem-security
  { id: 17, prompt: "Where does macOS malware most commonly establish persistence?", options: ["/tmp/LaunchAgents", "~/Library/LaunchAgents", "/usr/bin", "/Applications"], correctAnswer: "~/Library/LaunchAgents", explanation: "~/Library/LaunchAgents contains .plist files that run programs automatically on login. It requires no root access to write to, making it a common persistence location for user-level malware.", topicSlug: "filesystem-security", difficulty: "easy" },
  { id: 18, prompt: "What does 2>/dev/null do in a command?", options: ["Redirects all output to the screen", "Discards error messages silently", "Runs the command with double verbosity", "Sends output to a second terminal"], correctAnswer: "Discards error messages silently", explanation: "2> redirects stderr (error output). /dev/null is a black hole that discards anything written to it. Appending 2>/dev/null hides 'Permission denied' errors when searching as a non-root user.", topicSlug: "filesystem-security", difficulty: "medium" },
  { id: 19, prompt: "What does find / -mtime -1 find?", options: ["Files older than 1 day", "Files modified within the last 24 hours", "Files created in the last minute", "The most recently accessed file"], correctAnswer: "Files modified within the last 24 hours", explanation: "-mtime -1 means modified less than 1 day ago. This helps you find recently changed files, which is useful for spotting what an attacker or malicious installer touched.", topicSlug: "filesystem-security", difficulty: "medium" },
  { id: 20, prompt: "What makes world-writable files (-perm -002) a security risk?", options: ["They cannot be backed up", "Any user on the system can modify them", "They are invisible to the OS", "They run automatically on boot"], correctAnswer: "Any user on the system can modify them", explanation: "World-writable means the 'others' group has write permission. If a script or binary that runs as root is world-writable, any user can modify it to inject malicious commands.", topicSlug: "filesystem-security", difficulty: "medium" },
  { id: 21, prompt: "Which directory contains system-wide configuration files on Unix?", options: ["/bin", "/usr", "/etc", "/var"], correctAnswer: "/etc", explanation: "/etc holds configuration files for the entire system: /etc/passwd (users), /etc/sudoers (sudo rules), /etc/hosts (hostname resolution), and configs for most services.", topicSlug: "filesystem-security", difficulty: "easy" },
  { id: 22, prompt: "A .plist file in ~/Library/LaunchAgents references a binary in /tmp. What does this indicate?", options: ["A normal software update mechanism", "A strong red flag for malware persistence", "A macOS developer tool", "A system backup process"], correctAnswer: "A strong red flag for malware persistence", explanation: "Legitimate software installs binaries to /usr/local/bin, /Applications, or similar locations. Referencing a binary in /tmp is classic malware behavior since /tmp is world-writable and less scrutinized.", topicSlug: "filesystem-security", difficulty: "medium" },
  { id: 23, prompt: "What is the purpose of /var/log on a Linux system?", options: ["Virtual application runtime data", "System and application log files", "Variable-length archive storage", "Volatile user preferences"], correctAnswer: "System and application log files", explanation: "/var/log contains log files generated by the system and services: auth.log (authentication), syslog (general system), and application-specific logs.", topicSlug: "filesystem-security", difficulty: "easy" },
  { id: 24, prompt: "How do you list hidden dotfiles in your home directory?", options: ["ls ~/hidden", "find ~/ -type dot", "ls -la ~/.*", "ls -secret ~/"], correctAnswer: "ls -la ~/.*", explanation: "ls -la ~/.*  lists entries matching ~/.* which covers all dotfiles and dotfolders in your home directory. The -la flags give long format and include all files.", topicSlug: "filesystem-security", difficulty: "medium" },

  // networking-fundamentals
  { id: 25, prompt: "What IP address always refers to the local machine?", options: ["192.168.1.1", "10.0.0.1", "127.0.0.1", "0.0.0.0"], correctAnswer: "127.0.0.1", explanation: "127.0.0.1 (localhost) always points to the machine itself. A process connecting to 127.0.0.1 is communicating with another process on the same machine.", topicSlug: "networking-fundamentals", difficulty: "easy" },
  { id: 26, prompt: "What is the security difference between a service listening on 0.0.0.0 vs 127.0.0.1?", options: ["No difference, both are local only", "0.0.0.0 accepts connections from any interface including the network", "127.0.0.1 is more visible on the network", "0.0.0.0 requires a VPN to access"], correctAnswer: "0.0.0.0 accepts connections from any interface including the network", explanation: "Binding to 0.0.0.0 means accepting connections on all network interfaces, including your external IP. Binding to 127.0.0.1 means only local connections, which is safer for development services.", topicSlug: "networking-fundamentals", difficulty: "medium" },
  { id: 27, prompt: "What port does SSH use by default?", options: ["21", "22", "23", "443"], correctAnswer: "22", explanation: "SSH (Secure Shell) runs on TCP port 22 by default. If your Mac has Remote Login enabled in System Preferences, it is listening on port 22.", topicSlug: "networking-fundamentals", difficulty: "easy" },
  { id: 28, prompt: "What is the main security advantage of TCP over UDP from a monitoring perspective?", options: ["TCP is faster to analyze", "TCP connections have clear states like ESTABLISHED that appear in netstat", "TCP encrypts by default", "TCP connections use less bandwidth"], correctAnswer: "TCP connections have clear states like ESTABLISHED that appear in netstat", explanation: "TCP maintains connection state (SYN, ESTABLISHED, TIME_WAIT, etc.) which netstat can display. UDP is stateless, so ongoing UDP communication is harder to track this way.", topicSlug: "networking-fundamentals", difficulty: "medium" },
  { id: 29, prompt: "Why do ports below 1024 require root to open?", options: ["They are physically faster", "They are reserved well-known ports, requiring root prevents spoofing of standard services", "They have special encryption", "They are not routed by default"], correctAnswer: "They are reserved well-known ports, requiring root prevents spoofing of standard services", explanation: "A non-root user could otherwise start a fake SSH server on port 22 or a fake web server on port 80, intercepting connections meant for legitimate services.", topicSlug: "networking-fundamentals", difficulty: "medium" },
  { id: 30, prompt: "What does traceroute reveal?", options: ["Open ports on a remote host", "The network path (hops) between your machine and a destination", "The geographic location of an IP", "Active connections to your machine"], correctAnswer: "The network path (hops) between your machine and a destination", explanation: "traceroute shows each router hop between you and the destination. The first hop is typically your home router. Useful for diagnosing connectivity and understanding network topology.", topicSlug: "networking-fundamentals", difficulty: "easy" },
  { id: 31, prompt: "What port does HTTPS (encrypted web traffic) use?", options: ["80", "8080", "443", "8443"], correctAnswer: "443", explanation: "HTTP runs on port 80, HTTPS on port 443. If you see an unknown process listening on or connected to 443, it could be legitimate web traffic or could be malware using a trusted port.", topicSlug: "networking-fundamentals", difficulty: "easy" },

  // netstat
  { id: 32, prompt: "What does netstat -an show?", options: ["Only active connections", "Only listening ports", "All connections and listening ports with numeric IPs and ports", "All network interfaces"], correctAnswer: "All connections and listening ports with numeric IPs and ports", explanation: "-a shows all (listening and established), -n shows numbers instead of resolving hostnames and service names. This is the most useful form for security investigation.", topicSlug: "netstat", difficulty: "easy" },
  { id: 33, prompt: "What does a LISTEN state in netstat mean?", options: ["The process is downloading data", "The port is open and waiting for incoming connections", "The connection was recently closed", "The remote end has disconnected"], correctAnswer: "The port is open and waiting for incoming connections", explanation: "LISTEN means there is a process waiting on that port. Anyone who can reach that port on your machine can attempt to connect to it.", topicSlug: "netstat", difficulty: "easy" },
  { id: 34, prompt: "How do you filter netstat output to see only listening ports exposed beyond localhost?", options: ["netstat -an | grep 0.0.0.0", "netstat -an | grep LISTEN | grep -v '127.0.0.1'", "netstat -an | grep -i external", "netstat -listen"], correctAnswer: "netstat -an | grep LISTEN | grep -v '127.0.0.1'", explanation: "First grep filters to LISTEN entries, second grep removes localhost entries. What remains is listening on your external interface and potentially reachable from the network.", topicSlug: "netstat", difficulty: "medium" },
  { id: 35, prompt: "What does ESTABLISHED mean in netstat output?", options: ["The connection was terminated", "A connection is active and data can flow", "The process is listening for connections", "The connection is in progress"], correctAnswer: "A connection is active and data can flow", explanation: "ESTABLISHED means the TCP handshake completed and both sides can send data. If you see ESTABLISHED connections to IPs you do not recognize, investigate them.", topicSlug: "netstat", difficulty: "easy" },
  { id: 36, prompt: "Why is there a large number of TIME_WAIT entries in netstat output?", options: ["The system is infected with malware", "High traffic volume, connections recently closed and waiting for delayed packets", "A DDoS attack is in progress", "The firewall is dropping connections"], correctAnswer: "High traffic volume, connections recently closed and waiting for delayed packets", explanation: "TIME_WAIT is a normal TCP state after a connection closes. The OS keeps the connection in this state briefly to handle any delayed packets still in transit. Many TIME_WAIT entries just mean busy traffic.", topicSlug: "netstat", difficulty: "medium" },
  { id: 37, prompt: "On macOS, what does netstat -p specify?", options: ["The process name", "The protocol (tcp or udp)", "The port number", "The priority level"], correctAnswer: "The protocol (tcp or udp)", explanation: "On macOS, -p specifies the protocol: netstat -anp tcp shows only TCP. On Linux, -p means show the process name/PID. This is a common source of confusion.", topicSlug: "netstat", difficulty: "hard" },

  // lsof
  { id: 38, prompt: "What does lsof stand for?", options: ["List Open Firewalls", "Log Output Format", "List Open Files", "Linux Output Files"], correctAnswer: "List Open Files", explanation: "lsof lists open files. On Unix, almost everything is a file including network sockets, pipes, and devices. This makes lsof a powerful tool for seeing everything a process is doing.", topicSlug: "lsof", difficulty: "easy" },
  { id: 39, prompt: "What does lsof -i show?", options: ["Processes using internet/network connections", "All files larger than 1GB", "Processes belonging to root", "Interface statistics"], correctAnswer: "Processes using internet/network connections", explanation: "-i filters lsof to show only network-related open files (sockets). This maps process names and PIDs to their network connections.", topicSlug: "lsof", difficulty: "easy" },
  { id: 40, prompt: "How do you find what process is using port 443?", options: ["ps aux | grep 443", "netstat -p 443", "lsof -i :443", "who -port 443"], correctAnswer: "lsof -i :443", explanation: "lsof -i :443 shows all processes with a connection or socket on port 443. The -i :PORT syntax filters by port number.", topicSlug: "lsof", difficulty: "easy" },
  { id: 41, prompt: "Why run lsof with -P and -n flags for security investigation?", options: ["To show file sizes", "To avoid slow DNS and service name lookups, giving faster raw results", "To include root processes", "To show deleted files"], correctAnswer: "To avoid slow DNS and service name lookups, giving faster raw results", explanation: "-P shows numeric port numbers instead of service names, -n shows numeric IPs instead of hostnames. Both prevent potentially slow network lookups when you want quick results.", topicSlug: "lsof", difficulty: "medium" },
  { id: 42, prompt: "You found a suspicious connection in lsof with PID 1337. What command gives you full details on that process?", options: ["ls -l 1337", "ps -p 1337 -o user,pid,ppid,command", "kill -info 1337", "proc 1337 details"], correctAnswer: "ps -p 1337 -o user,pid,ppid,command", explanation: "ps -p PID -o user,pid,ppid,command shows who owns the process, its ID, its parent PID, and the full command that started it. The parent PID helps you trace how it was launched.", topicSlug: "lsof", difficulty: "medium" },
  { id: 43, prompt: "How do you see all open files and connections for a specific process PID?", options: ["lsof -i PID", "lsof -p PID", "ps -f PID", "open -l PID"], correctAnswer: "lsof -p PID", explanation: "lsof -p PID shows everything that specific process has open: config files, libraries, log files, network connections. A deep look into exactly what that process is touching.", topicSlug: "lsof", difficulty: "medium" },
  { id: 44, prompt: "What is the key advantage lsof has over netstat for identifying suspicious connections?", options: ["lsof shows more protocols", "lsof maps each connection to the exact process name and PID", "lsof is faster", "lsof shows connection speed"], correctAnswer: "lsof maps each connection to the exact process name and PID", explanation: "netstat shows connections and states but not always which process. lsof directly links each connection to the process responsible for it, making attribution immediate.", topicSlug: "lsof", difficulty: "medium" },

  // macos-persistence
  { id: 45, prompt: "What is a LaunchAgent on macOS?", options: ["A startup disk manager", "A .plist file that starts a program automatically when a user logs in", "Apple's cloud sync service", "A kernel extension"], correctAnswer: "A .plist file that starts a program automatically when a user logs in", explanation: "LaunchAgents are property list (.plist) files in specific Library folders. macOS reads them on login and starts the programs they reference automatically.", topicSlug: "system-persistence", difficulty: "easy" },
  { id: 46, prompt: "What is the difference between ~/Library/LaunchAgents and /Library/LaunchDaemons?", options: ["No functional difference", "LaunchAgents run per-user on login, LaunchDaemons run as root even before login", "LaunchDaemons need user approval, LaunchAgents do not", "LaunchAgents are for apps, LaunchDaemons are for scripts"], correctAnswer: "LaunchAgents run per-user on login, LaunchDaemons run as root even before login", explanation: "LaunchAgents run in the context of a logged-in user. LaunchDaemons run as root at system boot, before any user authenticates. Daemons have higher privilege.", topicSlug: "system-persistence", difficulty: "medium" },
  { id: 47, prompt: "How do you list all loaded launch entries excluding Apple's own?", options: ["launchctl list | grep com.apple", "launchctl show third-party", "launchctl list | grep -v com.apple", "ls /Library | grep -v apple"], correctAnswer: "launchctl list | grep -v com.apple", explanation: "Apple's own launch entries use com.apple as their label prefix. Filtering them out with grep -v leaves only third-party entries for you to review.", topicSlug: "system-persistence", difficulty: "easy" },
  { id: 48, prompt: "What command shows your scheduled cron jobs?", options: ["cron -list", "crontab -l", "cat /etc/cron", "schedule --show"], correctAnswer: "crontab -l", explanation: "crontab -l (lowercase L for list) prints your current user's crontab. Use sudo crontab -l to see root's scheduled jobs.", topicSlug: "system-persistence", difficulty: "easy" },
  { id: 49, prompt: "A new LaunchAgent appears after you connected to a public WiFi hotspot. What should you do?", options: ["Ignore it since it is probably a network optimization", "Investigate the entry, check what binary it runs and where that binary lives", "Restart your router", "Update macOS"], correctAnswer: "Investigate the entry, check what binary it runs and where that binary lives", explanation: "A LaunchAgent that appeared without you installing software is suspicious. Read the .plist file, check the program path, look up the label. Public WiFi is a common vector for drive-by attacks.", topicSlug: "system-persistence", difficulty: "medium" },
  { id: 50, prompt: "Why is a LaunchDaemon more dangerous than a LaunchAgent if abused by an attacker?", options: ["It runs more frequently", "It runs as root before login, giving full system access without user interaction", "It is harder to find", "It survives more reboots"], correctAnswer: "It runs as root before login, giving full system access without user interaction", explanation: "A malicious LaunchDaemon runs at boot as root. The attacker gets root persistence without ever needing the user to log in or interact.", topicSlug: "system-persistence", difficulty: "medium" },

  // users-permissions
  { id: 51, prompt: "What UID does the root user always have?", options: ["1", "100", "0", "999"], correctAnswer: "0", explanation: "UID 0 is root on all Unix systems. Any process with UID 0 has unlimited system privileges. If id shows uid=0, you are running as root.", topicSlug: "users-permissions", difficulty: "easy" },
  { id: 52, prompt: "What does sudo -l show?", options: ["The list of logged-in users", "Commands your user is permitted to run as root via sudo", "System logs from the last hour", "Running sudo processes"], correctAnswer: "Commands your user is permitted to run as root via sudo", explanation: "sudo -l shows your sudo privileges from /etc/sudoers. An attacker checks this first after gaining access to understand what escalation paths are available without cracking root's password.", topicSlug: "users-permissions", difficulty: "easy" },
  { id: 53, prompt: "What is a SUID binary?", options: ["A system update installer", "A binary that executes with the file owner's privileges (often root), not the caller's", "A signed Unix interface daemon", "A standard user ID configuration file"], correctAnswer: "A binary that executes with the file owner's privileges (often root), not the caller's", explanation: "SUID (Set User ID) binaries run as their file owner, not as the user who invoked them. If a SUID root binary can be exploited, it gives the attacker root access.", topicSlug: "users-permissions", difficulty: "medium" },
  { id: 54, prompt: "How do you find all SUID binaries on the system?", options: ["ls -suid /", "find / -perm -4000 -type f 2>/dev/null", "ps aux | grep suid", "chmod -find suid /"], correctAnswer: "find / -perm -4000 -type f 2>/dev/null", explanation: "-perm -4000 matches files with the SUID bit set. 2>/dev/null hides permission errors. SUID binaries in unusual locations (not /usr/bin or /bin) are red flags.", topicSlug: "users-permissions", difficulty: "medium" },
  { id: 55, prompt: "You see a new user account with UID 0 in /etc/passwd that you did not create. What does this mean?", options: ["A macOS update added it", "Your system is almost certainly compromised", "A standard service account", "A backup administrator account"], correctAnswer: "Your system is almost certainly compromised", explanation: "UID 0 = root. A second UID 0 account is a backdoor giving an attacker root access with a different username. This is a strong indicator of compromise.", topicSlug: "users-permissions", difficulty: "medium" },
  { id: 56, prompt: "What does the 'last' command show?", options: ["The last file modified", "Login and logout history from system logs", "The last command you ran", "The last sudo session"], correctAnswer: "Login and logout history from system logs", explanation: "last reads /var/log/wtmp and shows a history of logins, logouts, and reboots. Logins from unexpected IPs or at unusual hours are worth investigating.", topicSlug: "users-permissions", difficulty: "easy" },
  { id: 57, prompt: "What is privilege escalation?", options: ["Installing software as an admin", "A user gaining more privileges than they should have", "Upgrading a user account to paid tier", "Increasing a process's CPU priority"], correctAnswer: "A user gaining more privileges than they should have", explanation: "Privilege escalation is gaining elevated access beyond what was granted. A common attack goal is escalating from a regular user to root.", topicSlug: "users-permissions", difficulty: "easy" },

  // log-analysis
  { id: 58, prompt: "Where are authentication logs stored on Debian/Ubuntu Linux?", options: ["/var/log/system.log", "/var/log/auth.log", "/etc/log/auth", "/private/var/log/auth"], correctAnswer: "/var/log/auth.log", explanation: "auth.log on Debian/Ubuntu (and /var/log/secure on RHEL/CentOS) records SSH logins, sudo usage, su commands, and authentication failures.", topicSlug: "log-analysis", difficulty: "easy" },
  { id: 59, prompt: "What does tail -f /var/log/auth.log do?", options: ["Shows the last 10 lines once", "Prints the first lines of the file", "Streams new log entries in real time as they are written", "Follows symbolic links in the log directory"], correctAnswer: "Streams new log entries in real time as they are written", explanation: "-f (follow) watches the file and prints new lines as they appear. Useful for monitoring login attempts or sudo activity as it happens.", topicSlug: "log-analysis", difficulty: "easy" },
  { id: 60, prompt: "What grep command finds failed SSH login attempts on Linux?", options: ["grep 'SSH error' /var/log/syslog", "grep 'Failed password' /var/log/auth.log", "grep 'denied' /var/log/ssh.log", "grep 'Login failed' /var/log/secure"], correctAnswer: "grep 'Failed password' /var/log/auth.log", explanation: "SSH logs failed password attempts with this exact string. Many failed attempts in rapid succession indicate a brute force attack against your SSH server.", topicSlug: "log-analysis", difficulty: "easy" },
  { id: 61, prompt: "What macOS command shows recent system logs for the last hour?", options: ["cat /var/log/system", "log show --last 1h", "tail /private/var/log", "dmesg | tail"], correctAnswer: "log show --last 1h", explanation: "macOS uses a unified logging system. 'log show --last 1h' queries it for the past hour. Combine with --predicate to filter specific events.", topicSlug: "log-analysis", difficulty: "easy" },
  { id: 62, prompt: "Why is a gap in log files (missing time range) suspicious?", options: ["The system was probably in sleep mode", "The log rotation may have been too aggressive", "Attackers sometimes delete or truncate logs to hide their activity", "Log compression removed those entries"], correctAnswer: "Attackers sometimes delete or truncate logs to hide their activity", explanation: "Log deletion or truncation is a common post-compromise activity to remove evidence. A gap where continuous log entries should exist is a red flag for tampering.", topicSlug: "log-analysis", difficulty: "medium" },
  { id: 63, prompt: "What does grep -B 2 -A 2 'sudo' /var/log/auth.log do?", options: ["Shows only sudo lines", "Shows sudo lines plus 2 lines before and after each match for context", "Inverts the match for sudo lines", "Counts all sudo occurrences"], correctAnswer: "Shows sudo lines plus 2 lines before and after each match for context", explanation: "-B 2 shows 2 lines Before each match, -A 2 shows 2 lines After. This gives context around a log entry, helping you understand what happened immediately before and after.", topicSlug: "log-analysis", difficulty: "medium" },
  { id: 64, prompt: "How do you show all sudo activity in macOS logs from the last day?", options: ["grep sudo /var/log/system.log", "log show --predicate 'eventMessage contains \"sudo\"' --last 1d", "sudo log --list --today", "auditlog sudo --24h"], correctAnswer: "log show --predicate 'eventMessage contains \"sudo\"' --last 1d", explanation: "The --predicate flag filters macOS unified logs. eventMessage contains searches the message field. --last 1d covers 24 hours.", topicSlug: "log-analysis", difficulty: "medium" },

  // security-checklist
  { id: 65, prompt: "Why is establishing a baseline important for security monitoring?", options: ["It speeds up the system", "You need to know what normal looks like before you can recognize abnormal", "It creates a system restore point", "It encrypts your log files"], correctAnswer: "You need to know what normal looks like before you can recognize abnormal", explanation: "A baseline captures your system state when clean. Future comparisons to the baseline reveal changes that might indicate compromise, even subtle ones.", topicSlug: "security-checklist", difficulty: "easy" },
  { id: 66, prompt: "What does chmod +x script.sh do?", options: ["Creates a new script file", "Makes the script executable so you can run it", "Changes the script to run as root", "Compresses the script file"], correctAnswer: "Makes the script executable so you can run it", explanation: "+x adds execute permission. Without it you would get 'Permission denied' when trying to run ./script.sh even if the file exists and you own it.", topicSlug: "security-checklist", difficulty: "easy" },
  { id: 67, prompt: "How do you run a bash script in the current directory?", options: ["run script.sh", "execute ./script.sh", "./script.sh", "bash-run script.sh"], correctAnswer: "./script.sh", explanation: "The ./ prefix tells the shell to look in the current directory. The current directory (.) is not in $PATH by default for security reasons, so you must be explicit.", topicSlug: "security-checklist", difficulty: "easy" },
  { id: 68, prompt: "What does the diff command do?", options: ["Shows disk differences", "Compares two files and shows what is different between them", "Shows directory file count", "Displays file modification times"], correctAnswer: "Compares two files and shows what is different between them", explanation: "diff file1 file2 shows added, removed, and changed lines. Running diff baseline.txt current.txt on security scan outputs immediately shows what changed.", topicSlug: "security-checklist", difficulty: "easy" },
  { id: 69, prompt: "Which one-liner shows ports listening on non-localhost interfaces?", options: ["lsof -i --external", "netstat -an | grep LISTEN | grep -v '127.0.0.1'", "ps aux | grep LISTEN", "ss -l | grep external"], correctAnswer: "netstat -an | grep LISTEN | grep -v '127.0.0.1'", explanation: "First grep gets all LISTEN entries, second removes localhost. What remains is exposed to your network and potentially the internet.", topicSlug: "security-checklist", difficulty: "medium" },
  { id: 70, prompt: "Why run a security checklist on a clean system first, before any incidents?", options: ["To install security software", "To create a trusted baseline to compare future states against", "To train the OS to recognize threats", "To optimize system performance before an attack"], correctAnswer: "To create a trusted baseline to compare future states against", explanation: "Running the checklist when your system is known-good documents what normal looks like. Later runs can be diffed against this baseline to spot additions, removals, or changes.", topicSlug: "security-checklist", difficulty: "medium" },

  // c2-fundamentals
  { id: 71, prompt: "In a C2 architecture, which direction does the implant communicate?", options: ["It listens for inbound connections from the attacker", "It connects outbound to the attacker's handler server", "Both directions equally", "Only when triggered by a specific file on disk"], correctAnswer: "It connects outbound to the attacker's handler server", explanation: "Implants initiate outbound connections to the handler. Firewalls typically block unsolicited inbound connections but allow outbound traffic, so attackers design implants to call out rather than receive calls in.", topicSlug: "c2-fundamentals", difficulty: "easy" },
  { id: 72, prompt: "What is a beacon in C2 terminology?", options: ["A visible network broadcast packet", "An implant that sleeps, wakes at intervals, contacts the handler, and sleeps again", "A decoy process meant to attract attackers", "A firewall rule that signals suspicious traffic"], correctAnswer: "An implant that sleeps, wakes at intervals, contacts the handler, and sleeps again", explanation: "Beaconing produces low-volume periodic traffic that blends into background noise. The implant is mostly silent, activating only to check for commands and send results.", topicSlug: "c2-fundamentals", difficulty: "easy" },
  { id: 73, prompt: "What is jitter in a C2 beacon and why is it used?", options: ["Packet corruption to avoid firewall inspection", "Random variation in the beacon interval to defeat timing-based detection", "Encryption applied to beacon traffic", "A delay triggered when the user is active on the machine"], correctAnswer: "Random variation in the beacon interval to defeat timing-based detection", explanation: "Without jitter, a beacon connects at exactly the same interval every time, making it detectable by automated analysis. Jitter randomises the interval so simple pattern matching fails.", topicSlug: "c2-fundamentals", difficulty: "medium" },
  { id: 74, prompt: "Why do attackers use HTTPS (port 443) as a C2 channel?", options: ["Because it is the fastest protocol", "Because it blends with legitimate web traffic and encrypts the payload", "Because firewalls cannot detect port 443", "Because it requires no authentication"], correctAnswer: "Because it blends with legitimate web traffic and encrypts the payload", explanation: "Most networks have heavy HTTPS traffic. Port 443 is almost never blocked. TLS encryption hides the content from inspection. These factors make it the default choice for covert C2.", topicSlug: "c2-fundamentals", difficulty: "easy" },
  { id: 75, prompt: "How does DNS-based C2 carry commands and data without a TCP connection?", options: ["It uses UDP packets on port 53 as a raw data stream", "It encodes data in DNS query subdomains and reads responses from TXT or A records", "It hijacks the local DNS resolver and replaces responses", "It uses DNS cache poisoning to redirect traffic"], correctAnswer: "It encodes data in DNS query subdomains and reads responses from TXT or A records", explanation: "The implant sends data by querying subdomains like <base64data>.c2domain.com. The handler's DNS server receives these queries and responds with encoded commands in TXT records. No direct TCP connection is ever established.", topicSlug: "c2-fundamentals", difficulty: "medium" },
  { id: 76, prompt: "What is the key difference between a staged and a stageless C2 payload?", options: ["Staged payloads run faster", "A staged payload downloads the main implant after initial execution; stageless contains the full implant from the start", "Stageless payloads require admin rights", "Staged payloads only work on Windows"], correctAnswer: "A staged payload downloads the main implant after initial execution; stageless contains the full implant from the start", explanation: "Staged payloads are small and hard to detect initially, but the download step is a detectable network event. Stageless payloads are larger but operate fully without a second download.", topicSlug: "c2-fundamentals", difficulty: "hard" },

  // c2-network-detection
  { id: 77, prompt: "Which command best maps running processes to their outbound network connections?", options: ["ps aux | grep network", "netstat -an | grep ESTABLISHED", "sudo lsof -i -P -n | grep ESTABLISHED", "ss -l | grep process"], correctAnswer: "sudo lsof -i -P -n | grep ESTABLISHED", explanation: "lsof -i shows network connections with the responsible process name and PID. -P and -n avoid slow lookups. netstat shows connections but does not always show the process name without additional flags.", topicSlug: "c2-network-detection", difficulty: "easy" },
  { id: 78, prompt: "You run lsof and see 'bash' with an ESTABLISHED connection to 198.51.100.5:443. Why is this suspicious?", options: ["bash should use port 80, not 443", "bash has no legitimate reason to make network connections on its own", "The IP is in a reserved range", "443 is blocked by default on all systems"], correctAnswer: "bash has no legitimate reason to make network connections on its own", explanation: "bash is a shell interpreter, not a network application. An established connection from bash to an external IP strongly suggests it is being used as an interactive C2 shell or has been spawned by a malicious process.", topicSlug: "c2-network-detection", difficulty: "medium" },
  { id: 79, prompt: "Why might a single lsof check miss an active C2 beacon?", options: ["lsof does not show TCP connections", "A beaconing implant disconnects between call-home cycles and may be sleeping during your check", "lsof requires root to show any connections", "Encrypted connections do not appear in lsof output"], correctAnswer: "A beaconing implant disconnects between call-home cycles and may be sleeping during your check", explanation: "If the beacon interval is 5 minutes and you check in the 4 minutes 50 seconds of sleep time, you see no connection. Running two checks several minutes apart and comparing with diff catches the beacon when it reappears.", topicSlug: "c2-network-detection", difficulty: "medium" },
  { id: 80, prompt: "What DNS pattern strongly suggests DNS tunneling rather than normal browsing?", options: ["Queries for popular domains like google.com", "Multiple queries to the same base domain with long random-looking subdomains and TXT record lookups", "A single NXDOMAIN response", "Queries on UDP port 53 instead of TCP"], correctAnswer: "Multiple queries to the same base domain with long random-looking subdomains and TXT record lookups", explanation: "Normal DNS queries are short and resolve to known services. Long random subdomains carry encoded data. TXT record queries are uncommon in normal browsing. Together they are a clear sign of DNS tunneling.", topicSlug: "c2-network-detection", difficulty: "medium" },
  { id: 81, prompt: "You see python3 connecting to 203.0.113.5:443 and want to know what script it is running. Which command tells you?", options: ["file $(which python3)", "ps -p PID -o pid,ppid,user,args", "lsof -i :443", "netstat -anp | grep python"], correctAnswer: "ps -p PID -o pid,ppid,user,args", explanation: "ps -p PID -o args shows the full command including the script path. A legitimate Python process will reference a path in /usr/lib or a known application directory. A malicious one might show /tmp/.x.py or ~/.config/.update.py.", topicSlug: "c2-network-detection", difficulty: "medium" },
  { id: 82, prompt: "What does the ppid (parent process ID) tell you when investigating a suspicious process?", options: ["How much CPU the process is using", "Which process spawned it, revealing the infection chain", "When the process was last active", "The user permissions the process has"], correctAnswer: "Which process spawned it, revealing the infection chain", explanation: "The parent process shows how the suspicious process got started. A web server spawning bash suggests webshell execution. A cron job spawning python3 at an unexpected time suggests a planted scheduled task.", topicSlug: "c2-network-detection", difficulty: "medium" },

  // c2-process-injection
  { id: 83, prompt: "What is process injection in the context of C2 malware?", options: ["Creating a new process with a misleading name", "Placing attacker-controlled code into the memory space of a running legitimate process", "Injecting malicious entries into /etc/passwd", "Overwriting a process's log files"], correctAnswer: "Placing attacker-controlled code into the memory space of a running legitimate process", explanation: "The attacker's payload runs inside a legitimate process like sshd or python3. From ps the process looks normal. The anomaly shows up in unexpected network connections or file access that do not match the process's normal behavior.", topicSlug: "c2-process-injection", difficulty: "easy" },
  { id: 84, prompt: "On Linux, what does ls -la /proc/PID/exe showing '(deleted)' mean?", options: ["The process has been terminated", "The binary that started the process was deleted from disk after execution", "The process lacks read permissions on its own binary", "The process is running from a network share"], correctAnswer: "The binary that started the process was deleted from disk after execution", explanation: "A common evasion: drop the binary, run it, immediately delete the file. The process keeps running from memory. The (deleted) flag in /proc/PID/exe reveals this. Legitimate software rarely deletes its own binary while running.", topicSlug: "c2-process-injection", difficulty: "medium" },
  { id: 85, prompt: "In /proc/PID/maps, what makes an 'rwx' memory region suspicious in most processes?", options: ["It uses more memory than r-x regions", "Legitimate code regions are r-x only; rwx is needed for injected shellcode that must be written then executed", "rwx regions cannot be swapped to disk", "Only root processes should have rwx regions"], correctAnswer: "Legitimate code regions are r-x only; rwx is needed for injected shellcode that must be written then executed", explanation: "Code that is loaded from a file is mapped r-x. Code that an attacker writes into memory at runtime needs to be writable (w) to receive the payload and executable (x) to run it. JVMs and JIT compilers are the main legitimate exception.", topicSlug: "c2-process-injection", difficulty: "hard" },
  { id: 86, prompt: "Which parent-child process combination most strongly suggests webshell execution?", options: ["sshd spawning bash", "apache2 or nginx spawning bash or python3", "cron spawning a backup script", "su spawning a new shell"], correctAnswer: "apache2 or nginx spawning bash or python3", explanation: "A web server has no legitimate reason to spawn an interactive shell or scripting interpreter as a child process. This pattern almost always means an attacker uploaded a webshell and is executing system commands through the web server.", topicSlug: "c2-process-injection", difficulty: "medium" },
  { id: 87, prompt: "You find a .so shared library loaded by a process from /tmp/libupdate.so.1. Why is this a red flag?", options: ["Libraries cannot be loaded from /tmp", "Legitimate shared libraries belong in /lib or /usr/lib, not world-writable temporary directories", "The filename does not follow naming conventions", "Loading from /tmp requires root privileges"], correctAnswer: "Legitimate shared libraries belong in /lib or /usr/lib, not world-writable temporary directories", explanation: "/tmp is world-writable and cleared on reboot. A shared library there was almost certainly dropped by an attacker. Legitimate libraries are installed to standard paths by package managers.", topicSlug: "c2-process-injection", difficulty: "medium" },
  { id: 88, prompt: "What command helps you find all processes currently running from deleted binaries on Linux?", options: ["ps aux | grep deleted", "ls -la /proc/*/exe 2>/dev/null | grep deleted", "find /proc -name exe -deleted", "lsof | grep -i removed"], correctAnswer: "ls -la /proc/*/exe 2>/dev/null | grep deleted", explanation: "The /proc/PID/exe symlink points to the process's binary. If that binary was deleted, the symlink shows (deleted) after the path. Listing all processes at once with the wildcard * scans the entire process table in one command.", topicSlug: "c2-process-injection", difficulty: "medium" },
];
